routes/web.php
<?php

use Laravel\Socialite\Facades\Socialite as Socialize;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([

	"prefix" => app()->getLocale() . "-" . config("country.code")

], function ($route) {

	$route->get('/country/current', function () {
		$ip = request()->get("ip");
		return strtolower(geoip($ip)->iso_code);
	});

	$route->get('/google34e1137b7be403dc.html', function () {
		return response()->file(public_path('google34e1137b7be403dc.html'), [
			'Content-type' => 'text/html'
		]);
	});

	$route->get('/BingSiteAuth.xml', function () {
		return response()->file(public_path('BingSiteAuth.xml'), [
			'Content-type' => 'text/xml'
		]);
	});

	$route->get('/robots.txt', function () {
		return response()->file(public_path('robots.txt'), [
			'Content-type' => 'text/plain'
		]);
	});

	$route->get('/sitemap-ads.xml', function () {
		return response()->file(public_path('sitemap-ads.xml'), [
			'Content-type' => 'text/xml'
		]);
	});

	$route->get('/', ["as" => "home.index", "uses" => 'HomeController@index']);

	$route->get('/ads/{slug}', ["as" => "ads.details", "uses" => 'DetailsController@ad']);

	// Sitemaps
	$route->get('sitemap-update-index', ['as' => 'sitemap.update.index', 'uses' => 'SitemapController@indexUpdate']);;
	$route->get('sitemap-update-categories', ['as' => 'sitemap.update.categories', 'uses' => 'SitemapController@categoriesUpdate']);;
	$route->get('sitemap-update-videos', ['as' => 'sitemap.update.videos', 'uses' => 'SitemapController@videosUpdate']);;
	$route->get('sitemap-update-articles', ['as' => 'sitemap.update.articles', 'uses' => 'SitemapController@articlesUpdate']);;
	$route->get('sitemap-update-ads', ['as' => 'sitemap.update.ads', 'uses' => 'SitemapController@adsUpdate']);;
	$route->get('sitemap-update-tags', ['as' => 'sitemap.update.tags', 'uses' => 'SitemapController@tagsUpdate']);;
	$route->get('sitemap.xml', ['as' => 'sitemap.index', 'uses' => 'SitemapController@index']);;


	$route->get('/blog/{category_slug?}', ["as" => "posts.index", "uses" => 'PostsController@blog']);
	$route->get('/blog/{category_slug}/{slug}', ["as" => "posts.details", "uses" => 'DetailsController@article']);
	$route->get('/videos/{category_slug?}', ["as" => "videos.index", "uses" => 'PostsController@videos']);
	$route->get('/videos/{category_slug}/{slug}', ["as" => "videos.details", "uses" => 'DetailsController@video']);

	$route->get('/posts/paginate', ["as" => "posts.paginate", "uses" => 'PostsController@posts_paginate']);

	$route->any('/create_ad', ["as" => "ads.create", "uses" => 'AdsController@create']);
	$route->any('/verification/{user_id}', ["as" => "ads.verification", "uses" => 'AdsController@verification']);
	$route->any('/edit_ad/{id}', ["as" => "ads.edit", "uses" => 'AdsController@edit']);
	$route->any('/sold/{id}', ["as" => "ads.sold", "uses" => 'AdsController@sold']);

	// Comments
	$route->get('/comments/replies', ["as" => "comments.replies.index", "uses" => 'CommentController@replies']);
	$route->post('/comments/replies/add', ["as" => "comments.replies.add", "uses" => 'CommentController@addReply']);

	$route->get('/comments/{id}', ["as" => "comments.index", "uses" => 'CommentController@comments']);
	$route->post('/comments/{id}/add', ["as" => "comments.add", "uses" => 'CommentController@addComment']);

	/**
	 * Profile
	 */
	Route::group(['prefix' => 'profile'], function ($router) {
		// Offers
		$router->get('offers', ['as' => 'profile.offers.index', 'uses' => 'Profile\OffersController@index']);
		$router->post('offer', ['as' => 'profile.offers.add', 'uses' => 'Profile\OffersController@addOffer']);
		$router->post('offers/reply', ['as' => 'profile.offers.reply', 'uses' => 'Profile\OffersController@addReply']);
		$router->get('offers/replies', ['as' => 'profile.offers.replies', 'uses' => 'Profile\OffersController@getReplies']);
		$router->get('offers/json', ['as' => 'profile.offers.json', 'uses' => 'Profile\OffersController@getOffersJson']);

		// Ads
		$router->get('ads', ['as' => 'profile.ads.index', 'uses' => 'AdsController@myAds']);

		$router->get('favourites', ['as' => 'profile.ads.favourites', 'uses' => 'AdsController@my_favourites']);


		//Users
		$router->any('edit', ['as' => 'profile.edit.form', 'uses' => 'Profile\UserController@profileEdit']);

	});
	/**
	 * Auth
	 */

	Route::any('/login', "AuthController@login")->name("login");
	Route::any('/activation/{code?}', "AuthController@activation")->name("activation");
	Route::any('/register', "AuthController@register")->name("register");
	Route::any('/forget_password', "AuthController@forget_password")->name("forget_password");
	Route::get('/logout', "AuthController@logout")->name("logout");
	Route::get('/login/facebook', "AuthController@facebook");
	Route::get('/login/twitter', "AuthController@twitter");
	Route::get('/login/google', "AuthController@google");

	Route::group(['prefix' => 'auth'], function ($route) {

		Session::put("previous_url", URL::previous());

		$route->get('facebook', function () {
			return Socialize::driver('facebook')->redirect();
		})->name("facebook.login");

		$route->get('twitter', function () {
			return Socialize::driver('twitter')->redirect();
		})->name("twitter.login");

		$route->get('google', function () {
			return Socialize::driver('google')->redirect();
		})->name("google.login");

	});

	Route::prefix('ajax')->group(function ($route) {
		$route->get('/search_ads', ["as" => "ajax.search_ads", "uses" => 'AjaxController@search_ads']);
		$route->get('/search_cities', ["as" => "ajax.search_cities", "uses" => 'AjaxController@search_cities']);
		$route->get('/get_sub_categories', ["as" => "ajax.get_sub_categories", "uses" => 'AjaxController@get_sub_categories']);
		$route->get('/mob_get_sub_categories', ["as" => "ajax.mob_get_sub_categories", "uses" => 'AjaxController@mob_get_sub_categories']);
		$route->get('/search_get_sub_categories', ["as" => "ajax.search_get_sub_categories", "uses" => 'AjaxController@search_get_sub_categories']);
		$route->get('/ca_get_sub_categories', ["as" => "ajax.ca_get_sub_categories", "uses" => 'AjaxController@ca_get_sub_categories']);
		$route->get('/like', ["as" => "ajax.like", "uses" => 'AjaxController@like']);
		$route->get('/get_sub_places', ["as" => "ajax.sub_places", "uses" => 'AjaxController@get_sub_places']);
		$route->post('/image_upload', ["as" => "ajax.image_upload", "uses" => 'AjaxController@image_upload']);
		$route->post('/video_upload', ["as" => "ajax.video_upload", "uses" => 'AjaxController@video_upload']);
		$route->get('/regions', ["as" => "ajax.regions", "uses" => 'AjaxController@get_regions']);
	});

	Route::get('/media/regenerate/{offset?}', ['as' => 'media.cron', 'uses' => 'MediaRegenerator@regenerate_media']);

	Route::get('/media/resize/{id?}', ['as' => 'media.resize', 'uses' => 'MediaRegenerator@resize']);

	Route::get('/reindex/{offset?}', ['as' => 'index.cron', 'uses' => 'IndexController@index']);
	Route::get('/ads_shift/{offset?}', ['as' => 'scripts.ads_shift', 'uses' => 'ScriptsController@ads_shift']);

	Route::get('/search', ['as' => 'search.index', 'uses' => 'SearchController@index']);

	Route::get('/search_paginate', ['as' => 'search.paginate', 'uses' => 'SearchController@search_paginate']);

	Route::get('/sub_category_paginate', ['as' => 'category.sub_category_paginate', 'uses' => 'CategoryController@sub_category_paginate']);


	Route::get('/page/{slug}', ['as' => 'page.index', 'uses' => 'DetailsController@page']);

	Route::get('/gdpr', ['as' => 'pages.gdpr', 'uses' => function () {
		$page = \App\Models\Page::withoutGlobalScopes()->where('slug', 'gdpr')->where('status', 1)->first();

		if (!$page) {
			abort(404);
		}

		return view('page', ['page' => $page]);
	}]);

	Route::any('/contact_us', ['as' => 'contact_us', 'uses' => 'HomeController@contact_us']);
	// Tags
	Route::get('/tag/{slug}', ['as' => 'tag.index', 'uses' => 'TagsController@index']);
	Route::get('/tag/{slug}/paginate', ['as' => 'tag.paginate', 'uses' => 'TagsController@tags_paginate']);


	Route::get('/test_mail', ['uses' => function () {


		$user = \App\User::first();

		\Illuminate\Support\Facades\Mail::to('ebtehalshemais@gmail.com')->send(new \App\Mail\UserActivationMail($user));
		\Illuminate\Support\Facades\Mail::to('ebtehal.shemais@gmail.com')->send(new \App\Mail\UserActivationMail($user));

//        \Illuminate\Support\Facades\Mail::send('emails.activation', ["user" => $user], function ($message) use ($user) {
//            $message->to('mostafa.elbardeny@gmail.com', 'teffa')->subject('تفعيل الحساب');
//        });
	}]);

	Route::get('/users_mig', ['uses' => function () {
		$t = \Pusher::trigger('public-notifications-channel', 'new-content', ['title' => 'hhhhhh', 'message' => 'uuuuuuuu', 'object_url' => '5555555']);
		dd($t);
		$x = new \Dot\Ads\Jobs\NotificationJob('livestream', 0, \Dot\Options\Facades\Option::get('livestream_url'));
		$x->handle();
		die;
		dispatch(new \Dot\Ads\Jobs\NotificationJob('new_article'));
		die;

		$api_key = 'AIzaSyCOprMrY4U6QRirrg5SGOmkg1Rj5xyagPM';

		$legacy_server_key = 'AIzaSyDGY1rKbHYB5xo4tSKOCwgc9fHXRFlH80g';

		$fcmUrl = 'https://fcm.googleapis.com/fcm/send';

		$token = 'dgzFwDgb1Wo:APA91bGvEJ711ibA7r1u2cAivv8xRN2HWPcmjq53u5PhDF5te49Kx0YHsKrLKNV7gXm3kvZwIhndOpJ7UiI0Am0g1WpMylOkL7CswFKXRxrHb6p-an11Iz0mpVAar13muNK3M6vApkyCrGIo4Dp-UzsjemnV-roSIQ';


		$notification = [
			'title' => 'blah blah blah',
			'body' => 'this is test',
			'sound' => true,
		];

		$extraNotificationData = ["message" => 'testing new', "type" => '5'];

		$temp = [
			'to' => $token,
			'notification' => $notification,
			'data' => $extraNotificationData
		];

		$options = [

app/Models/Api/Ads.php
<?php

namespace App\Models\Api;

use App\Models\Media;
use Basemkhirat\Elasticsearch\Model;
use Illuminate\Support\Facades\DB;

/**
 * Class Ad
 *
 * @package App\Indices
 */
class Ads extends Model
{

    /**
     * @var string
     */
    protected $index = "dubarter";

    /**
     * @var string
     */
    protected $type = "ads";

    /**
     * @var array
     */
    protected $casts = ['currency' => 'json'];
    protected $appends = ["real_views", 'isLiked'];


    public function adsLikes()
    {
        return $this->belongsToMany(Ads::class, 'ads_likes', 'user_id', 'ad_id');
    }

    public function scopeLatest($query, $column = "created_at", $order = "DESC")
    {
        $query->orderBy($column, $order);
    }

    public function scopeFeatured($query)
    {
        $query->where("featured", 1);
    }

    public function getRealViewsAttribute()
    {
        $ad = DB::table('ads')->where('id', $this->_id)->select('views')->first();

        return $ad ? $ad->views : 0;
    }

    function getMainImageAttribute()
    {
        $image = null;

        if (count($this->files)) {
            if ($this->files[0]['type'] == 'image') {
                $image = $this->files[0]['path'];
            } else {
                return "";
            }
        }

        return $image;
    }

    public function getFilesAttribute($files)
    {
        $arr = [];

        foreach ($files as $k => $file) {

            $temp = [];

            if ($file['type'] == 'image') {

                $temp['id'] = $file['id'];
                $temp['type'] = $file['type'];
                $temp['medium'] = thumbnail($file['path'], 'medium');
                $temp['thumb'] = thumbnail($file['path'], 'thumbnail');

            } else if ($file['type'] == 'video') {

                $temp['id'] = $file['id'];
                $temp['type'] = $file['type'];

                $temp['provider'] = $file['provider'];

                if ($file['provider'] == 'youtube') {
                    $temp['path'] = $file['path'];
                } else {
                    $temp['path'] = uploads_url($file['path']);
                }

                $temp['provider_image'] = $file['provider_image'];

            }

            if (count($temp)) {
                $arr[] = $temp;
            }
        }

        if (!count($arr)) {
            $media = Media::where('id', 0)->first();

            if ($media) {
                $temp = [];

                $temp['id'] = $media->id;
                $temp['type'] = $media->type;
                $temp['medium'] = thumbnail($media->path, 'medium');
                $temp['thumb'] = thumbnail($media->path, 'thumbnail');

                $arr[] = $temp;
            }
        }

        return $arr;
    }

    public function getCountryAttribute($country)
    {
        $arr = [];
        $arr['id'] = $country['id'];
        $arr['code'] = $country['code'];
        $arr['name'] = $country['name'];
        return $arr;
    }

    public function getCityAttribute($city)
    {
        $arr['id'] = $city['id'];
        $arr['name'] = $city['name'];
        return $arr;
    }

    public function getCategoriesAttribute($categories)
    {
        $arr = [];
        foreach ($categories as $k => $category) {
            $arr[$k]['id'] = $category['id'];
            $arr[$k]['name'] = $category['name'];
            $arr[$k]['slug'] = $category['slug'];
            $arr[$k]['direct'] = $category['direct'];
        }
        return $arr;
    }

    public function getAttrsAttribute($attributes)
    {
        $i = 0;
        $arr = [];
        foreach ($attributes as $k => $attribute) {
            $temp = $this->getAttrib($k);

            $arr[$i]['slug'] = $k;
            $arr[$i]['name'] = $temp ? $temp->name : null;
            $arr[$i]['small_icon'] = $temp ? $temp->small_icon : "";
            $arr[$i]['big_icon'] = $temp ? $temp->big_icon : "";
            $arr[$i]['big_icon_id'] = $temp ? $temp->big_icon_id : 0;
            $arr[$i]['small_icon_id'] = $temp ? $temp->small_icon_id : 0;

            $arr[$i]['value'] = null;
            $arr[$i]['options'] = [];

            if (is_array($attribute) && count($attribute)) {
                $arr[$i]['value'] = $attribute[0];

                foreach ($attribute as $atv) {
                    if ($temp->options && count($temp->options)) {

                        foreach ($temp->options as $op) {
                            if (isset($op['slug']) && $op['slug'] == $atv) {
                                $arr[$i]['options'][] = $op;
                            }
                        }
                    }
                }
            }

            $i++;
        }
        return $arr;
    }

    public function getAttrib($slug)
    {
        return Attributes::where('slug', $slug)->first();
    }

    public function getCreatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->timestamp;
    }

    public function getUpdatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->timestamp;
    }

    public function getPublishedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->timestamp;
    }

    public function getExpiredAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->timestamp;
    }


    public function getIsLikedAttribute()
    {
        $auth = auth()->guard('mobile-api');
        if (!$auth->check()) {
            return false;
        }
        $liked = AdsLikes::where('ad_id', $this->_id)->where('user_id', $auth->user()->id)->first();
        return ($liked) ? true : false;
    }

    public function likes()
    {
        return $this->hasMany(AdsLikes::class, 'ad_id', '_id');
    }

    /************* Json Translate *************/
    /*public function getCurrencyAttribute($currency)
    {
        return $this->translate($currency);
    }*/

    private function decode($string)
    {
        return ($string) ? json_decode($string) : null;
    }

    private function translate($source)
    {
        return ($source) ? $source[app()->getLocale()] : null;
    }

    public function boot($query)
    {
        //$query->where("status", 1);
        $query->where('published_at', ">=", '2018-01-01 00:00:00');
    }

    function scopeByCountry($query, $id)
    {
        $query->where(function ($query) use ($id) {
            $query->where('country_id', $id)
                ->orWhere('country_id', 0);
        });
    }

}

resources/views/partials/home/cars.blade.php
<section id="auto-barter">
    <div class="container">
        <h4 class="text-center font-weight-bold py-4 mb-0"><a
                    href="{{ $ms_main_cats->where('id', \App\Models\Category::AUTOBARTER)->first()->url }}">{{ $ms_main_cats->where('id', \App\Models\Category::AUTOBARTER)->first()->custom_name }}</a>
        </h4>

        @include('partials.home.sections_search_bar', ['category_id' => \App\Models\Category::AUTOBARTER])

        <ul class="nav nav-pills justify-content-center m-0" id="pills-tab" role="tablist">

            @foreach($featured_cars as $type => $ads)
                <li class="nav-item">
                    <a class="nav-link {{ $loop->first ? 'active' : '' }}" id="pills-{{ $type }}-tab" data-toggle="pill"
                       href="#pills-{{ $type }}" role="tab"
                       aria-controls="pills-{{ $type }}"
                       aria-selected="{{ $loop->first ? 'true' : 'false' }}">{{ trans('home.' . $type) }}</a>
                </li>
            @endforeach

        </ul>
        <div class="tab-content" id="pills-tabContent">

            @foreach($featured_cars as $type => $ads)

                <div class="tab-pane fade show {{ $loop->first ? 'active' : '' }}" id="pills-{{ $type }}"
                     role="tabpanel"
                     aria-labelledby="pills-{{ $type }}-tab">
                    <div class="owl-carousel owl-theme">
                        @if(count($ads))
                            @foreach($ads as $ad)

                                @include('partials.ad.ad_card', ['ad' => $ad])

                            @endforeach
                        @endif
                    </div>
                </div>

            @endforeach

        </div>
        <div class="advertise">

            <!-- responsive ads replaced 728*90 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-9085617575772553"
                 data-ad-slot="5498890495"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>

        </div>
    </div>
    <a href="#aqura-barter" class="scroll-section">
        <span class="d-block">{{ $ms_main_cats->where('id', \App\Models\Category::AQARBARTETR)->first()->name }}</span>
        <img src="{{ assets("frontend") }}/assets/img/chevron-bottom.png" alt="">
    </a>
</section>

resources/views/partials/home/food.blade.php
<section id="food-barter">
    <div class="container">
        <h4 class="text-center font-weight-bold mb-0"><a href="{{ $ms_main_cats->where('id', \App\Models\Category::FOODBARTER)->first()->url }}">{{ $ms_main_cats->where('id', \App\Models\Category::FOODBARTER)->first()->custom_name }}</a></h4>

        @include('partials.home.sections_search_bar', ['category_id' => \App\Models\Category::FOODBARTER])

        <div class="filter-search">
            <div class="row">
                @if($day_restaurant)
                    <div class="col-md-4">
                        <div class="card food-card">

                            <a href="{{ $day_restaurant->url }}" class="item-name"><img src="{{ assets("frontend") }}/assets/img/placeholder-today-restaurant.jpg" data-src="{{ $day_restaurant->main_image ? thumbnail($day_restaurant->main_image, "medium") : '' }}" alt="{{ $day_restaurant->title }}" class="img-fluid lzd-image"></a>

                        </div>
                    </div>
                    <div class="col-md-5">
                        <h5 class="font-weight-bold p-0 mb-0">{{ trans('home.today-rest') }}</h5>
                        <hr class="mb-2">
                        <div class="resturant-info">
                            <h6 class="mb-3">
                                <a href="{{ $day_restaurant->url }}">
                                    {{ $day_restaurant->title }}
                                </a>
                            </h6>
                            <div>
                                <div class="card resturant-logo d-inline-block">

                                    <a href="{{ $day_restaurant->url }}" class="item-name"><img src="{{ assets("frontend") }}/assets/img/placeholder-today-restaurant-thumb.jpg" data-src="{{ $day_restaurant->main_image ? thumbnail($day_restaurant->main_image) : '' }}" alt="" class="img-fluid lzd-image"></a>
                                </div>
                                <div class="resturant-desc">
                                    <p class="mb-2">
                                        {{ str_limit(strip_tags($day_restaurant->content), 200) }}
                                    </p>
                                    <bdi class="rate">
                                        <span>4</span> / 5
                                    </bdi>
                                    <bdi class="star mx-2">
                                        <a class="start-icon star-full">
                                            <i class="fas fa-star"></i>
                                        </a>
                                        <a class="start-icon star-full">
                                            <i class="fas fa-star"></i>
                                        </a>
                                        <a class="start-icon star-full">
                                            <i class="fas fa-star"></i>
                                        </a>
                                        <a class="start-icon star-full">
                                            <i class="fas fa-star"></i>
                                        </a>
                                        <a class="start-icon star-empty">
                                            <i class="fas fa-star"></i>
                                        </a>
                                    </bdi>
                                    <bdi class="views d-block mt-2"><span class="eye-icon"><i class="fas fa-eye"></i><span class="viewer-count">12.295</span>
                                    </bdi>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="col-md-3 restaurant-sidebar">

                    <ul class="list-unstyled">

                        @foreach($latest_restaurants as $restaurant)
                            <li class="row restaurant-row">
                                <div class="restaurant-row-image">

                                    <a href="{{ $restaurant->url }}" class="item-name"><img class="lzd-image" src="{{ assets("frontend") }}/assets/img/placeholder-restaurant-sidebar.jpg" data-src="{{ $restaurant->main_image ? thumbnail($restaurant->main_image) : '' }}" alt=""></a>

                                </div>

                                <div class="restaurant-row-title">
                                    <a href="{{ $restaurant->url }}">{{ $restaurant->title }}</a>
                                    <span>{{ isset($restaurant->attrs['branches-count']) ? $restaurant->attrs['branches-count'][0] : 0 }} فرع </span>
                                </div>
                            </li>
                        @endforeach

                    </ul>

                    <a href="{{ $kitchen_category->url }}" class="more-restaurants">
                        {{ trans('home.rests-link') }}<span class="icon-duble-angle {{ app()->getLocale() == 'ar' ? 'mr-2' : 'ml-2' }}"><i
                                    class="fas fa-angle-double-{{ app()->getLocale() == 'ar' ? 'left' : 'right' }}"></i></span>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="restaurants-box card">
                        <ul class="restaurants-list list-unstyled mb-0 p-0">

                            @foreach($featured_restaurants as $restaurant)
                                <li>
                                    <a href="{{ $restaurant->url }}">
                                        <img class="lzd-image" src="{{ assets("frontend") }}/assets/img/placeholder-restaurant-bar.jpg" data-src="{{ $restaurant->main_image ? thumbnail($restaurant->main_image) : '' }}"/>
                                    </a>
                                </li>
                            @endforeach

                        </ul>

                    </div>
                </div>
            </div>
        </div>
        <div class="advertise">

            <!-- responsive ads replaced 728*90 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-9085617575772553"
                 data-ad-slot="5498890495"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>

        </div>
    </div>

    <a href="#blog-barter" class="scroll-section">
        <span class="d-block">{{trans('home.classifieds')}}</span>
        <img src="{{ assets("frontend") }}/assets/img/chevron-bottom.png" alt="">
    </a>
</section>

resources/views/partials/home/style_1.blade.php
<section id="style-barter">
    <div class="container">
        <h4 class="text-center font-weight-bold mb-0"><a href="{{ $ms_main_cats->where('id', \App\Models\Category::STYLEBARTER)->first()->url }}">{{ $ms_main_cats->where('id', \App\Models\Category::STYLEBARTER)->first()->name }}</a></h4>
        <div class="filter">
            <form method="get" action="{{ route('search.index') }}">
                <div class="row justify-content-md-center">
                    <div class="col-lg-10">
                        <div class="col-sm-5">
                            <input type="text" class="home-search-input" name="q"
                                   placeholder="{{ trans('home.search_for') }} ....">
                        </div>
                      <div class="col-sm-5">
                            <select class="choose-city select2-dropdown" name="city_id" aria-placeholder="">
                                <option value="">{{ trans("home.city") }}</option>
                                @if(count($cities))
                                    @foreach($cities as $city)
                                        <option value="{{ $city->id }}">{{ $city->name }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>

                        <input type="hidden" name="category_id" value="{{ \App\Models\Category::STYLEBARTER }}" />
                        <div class="col-sm-2">
                          <button type="submit" class="search-icon btn"><img
                                    src="{{ assets("frontend") }}/assets/img/search-icon.png"
                                    alt=""></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>


        <div class="filter-result">
            <div class="row">
                <div class="col-md-8">
                    <div class="owl-carousel style-barter owl-theme">
                        @if(count($style_slider_ads))
                            @foreach($style_slider_ads as $ad)
                                <div class="item">
                                    <a href="{{ $ad->url }}">
                                        <div class="card custom-box mb-0">
                                            <div class="card-img-header">
                                                <a href="{{ $ad->url }}">
                                                    <img src="{{ $ad->main_image ? thumbnail($ad->main_image) : '' }}"
                                                                                                            alt="{{ $ad->title }}" class="img-fluid">
                                                </a>
                                            </div>
                                            <div class="card-body">
                                                <a href="{{ $ad->url }}" class="item-name">{{ $ad->title }}</a>
                                                <div class="item-price">
                                                    <span class="quantity">{{ $ad->price }}</span>
                                                    <span class="currancy">{{ $ad->currency }}</span>
                                                </div>

                                                <div class="item-detailes">

                                                    @foreach(array_slice($ad->attributes, 0, 3) as $attribute)
                                                        <div class="icon-box">
                                                            <img src="{{ $attribute->small_icon_url }}" alt="" class="icon">
                                                            <span>{{ $attribute->value_title }}</span>
                                                        </div>
                                                    @endforeach

                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            @endforeach
                        @endif
                    </div>
                    <div class="shope-here text-center">
                        <a href="{{ $ms_main_cats->where('id', \App\Models\Category::STYLEBARTER)->first()->url }}">{{ trans("home.style_shop_here") }}</a>
                    </div>

                </div>
                <div class="col-md-4">
                    @if($style_featured_article)
                        <div class="card custom-box style-artical mb-0">
                            <div class="card-img-header">
                                <img class="img-fluid"
                                     src="{{ $style_featured_article->image ? thumbnail($style_featured_article->image->path, "medium") : '' }}"
                                     alt="{{ $style_featured_article->title }}">
                            </div>

                            <div class="card-body">
                                <a href="{{ $style_featured_article->url }}" class="item-name">
                                    {{ $style_featured_article->title }}
                                </a>
                                <p class="card-text">{{ $style_featured_article->excerpt }}</p>
                            </div>
                        </div>
                    @endif

                </div>

            </div>
        </div>
        <div class="advertise">
            <img src="{{ assets("frontend") }}/assets/img/ads1.png" alt="" class="img-fluid">
        </div>
    </div>

    <a href="#food-barter" class="scroll-section">
        <span class="d-block">{{ $ms_main_cats->where('id', \App\Models\Category::FOODBARTER)->first()->name }}</span>
        <img src="{{ assets("frontend") }}/assets/img/chevron-bottom.png" alt="">
    </a>
</section>